
pocd_nodes = [
              {:host => "cm571-template1", :ip => "10.10.45.10", :box => "boxcutter/centos67", :gui => false, :ram => 10240, :cpu => 10},
            #  { :host => "cm571-template2", :ip => "192.168.1.113", :box => "boxcutter/centos67", :gui => false, :ram => 10240, :cpu => 10},
              #{:host => "cm571-template3", :ip => "192.168.1.114", :box => "boxcutter/centos67", :gui => false, :ram => 10240, :cpu => 10}
]
varDomain = "xpoint.internal"
varHostEntries = ""
varRepository = "E:/Barclays/VAGRANT_PROJECT/REPOSITORY/"
pocd_nodes.each do |pocd_node|
    varHostEntries << "#{pocd_node[:ip]} #{pocd_node[:host]}.#{varDomain} #{pocd_node[:host]}\n"
end
#Now pass hostfile content into /etc/hosts
$etchosts = <<SCRIPT
#!/bin/bash
cat > /etc/hosts <<EOF
127.0.0.1       localhost
10.10.45.1     host.#{varDomain} host
#{varHostEntries}
EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  pocd_nodes.each do |pocd_node|
  config.vm.define pocd_node [:host] do |pocd_config|

    pocd_config.vm.box = pocd_node [:box]

    pocd_config.vm.network "private_network", ip: pocd_node[:ip], :netmask => "255.255.255.0"
    pocd_config.vm.hostname = "#{pocd_node [:host]}.#{varDomain}"
    pocd_config.hostmanager.aliases = "#{pocd_node[:host]}"
    pocd_config.vm.provider :virtualbox do |v|
      v.name = pocd_node[:host].to_s
      v.gui = pocd_node[:gui]
      v.customize ["modifyvm", :id, "--memory", pocd_node[:ram].to_s]
      v.customize ["modifyvm", :id, "--cpus", pocd_node[:cpu].to_s]
    end

    pocd_config.vm.synced_folder varRepository, "/repository",
      id: "repository",
      owner: "vagrant",
      group: "vagrant"
    #"Configuring Java", "Inserting hostnames in /etc/hosts"
      pocd_config.vm.provision :shell, :path => "deployJava/provision_for_java.sh"
      pocd_config.vm.provision :shell, :inline => $etchosts
      puts "Starting Cloudera Manager Deployment using RPMS"
      pocd_config.vm.provision :shell, :path => "deployClouderaRepo/provision_rpm_cm572.sh"

    end
  end
end
