---
# defaults file for mysql
mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: "root"

mysql_db:
     - name: oozie
     - name: hive
     - name: hue
     - name: amon
     - name: rman
mysql_users:
     - name: oozie
       pass: oozie
       priv: "*.*:ALL"
     - name: hive
       pass: hive
       priv: "*.*:ALL"
     - name: hue
       pass: hue
       priv: "*.*:ALL"
     - name: amon
       pass: amon
       priv: "*.*:ALL"
     - name: rman
       pass: rman
       priv: "*.*:ALL"
mysql_sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
